replace static inclusion of fixtures modules with .fixtures.yml
There was a report of the forge distribution failing on #puppet today
(2013-06-18) which appears to be due to symlinks under spec/fixtures/*

    # puppet module install haraldsk/nfs --force --trace
    Notice: Preparing to install into /etc/puppet/modules ...
    Notice: Downloading from http://forge.puppetlabs.com ...
    Notice: Installing -- do not interrupt ...
    Error: No such file or directory -
    /etc/puppet/modules/nfs/spec/fixtures/modules/nfs/files

Also convert Rakefile & spec/spec_helper.rb to use
puppetlabs_spec_helper.